
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Dostawy_szczegoly
{

    public int Id_dostawy { get; set; }

    public string Etykieta_produktu { get; set; }

    public string Cena_pozycji { get; set; }

    public string Ilosc_dostarczonych { get; set; }



    public virtual Dostawy Dostawy { get; set; }

    public virtual Magazyn_glowny Magazyn_glowny { get; set; }

}

}
