
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Dostawy
{

    public int Id_dostawy { get; set; }

    public string Id_dostawcy { get; set; }

    public string Data_odbioru { get; set; }

    public string Koszt { get; set; }

    public string Id_faktury { get; set; }



    public virtual Dostawy_szczegoly Dostawy_szczegoly { get; set; }

    public virtual Dostawcy Dostawcy { get; set; }

    public virtual Faktury Faktury { get; set; }

}

}
