
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Faktury
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Faktury()
    {

        this.Dostawy = new HashSet<Dostawy>();

        this.Klienci = new HashSet<Klienci>();

        this.Zamowienia = new HashSet<Zamowienia>();

    }


    public int Id_faktury { get; set; }

    public string Id_klienta { get; set; }

    public string Sposob_platnosci { get; set; }

    public string Termin_platnosci { get; set; }

    public string Data_wystawienia { get; set; }

    public string Status_faktury { get; set; }

    public string Typ_faktury { get; set; }

    public string Rozdaj_faktury { get; set; }

    public string Rabat { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dostawy> Dostawy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Klienci> Klienci { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zamowienia> Zamowienia { get; set; }

}

}
