
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Identyfikatory_produktow
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Identyfikatory_produktow()
    {

        this.Magazyn_glowny = new HashSet<Magazyn_glowny>();

        this.Zamowienia = new HashSet<Zamowienia>();

    }


    public int Id_produktu { get; set; }

    public string Id_kategorii { get; set; }

    public string Nazwa_produktu { get; set; }

    public string Wartosc_jednostkowa { get; set; }

    public string Wartosc_cechy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Magazyn_glowny> Magazyn_glowny { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zamowienia> Zamowienia { get; set; }

    public virtual Kategorie_produktow Kategorie_produktow { get; set; }

}

}
