
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Klienci
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klienci()
    {

        this.Faktury = new HashSet<Faktury>();

        this.Zamowienia = new HashSet<Zamowienia>();

    }


    public int Id_klienta { get; set; }

    public string Nazwisko { get; set; }

    public string Imie { get; set; }

    public string Nazwa_firmy { get; set; }

    public string Kod_pocztowy { get; set; }

    public string Miasto { get; set; }

    public string Ulica { get; set; }

    public string Nr_domu { get; set; }

    public string Nr_lokalu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Faktury> Faktury { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zamowienia> Zamowienia { get; set; }

}

}
