
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Magazyn_glowny
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Magazyn_glowny()
    {

        this.Dostawy_szczegoly = new HashSet<Dostawy_szczegoly>();

    }


    public int Etykieta_produktu { get; set; }

    public string Id_dostawcy { get; set; }

    public string Ilosc_na_stanie { get; set; }

    public string Id_kategorii { get; set; }

    public string Id_produktu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dostawy_szczegoly> Dostawy_szczegoly { get; set; }

    public virtual Dostawcy Dostawcy { get; set; }

    public virtual Identyfikatory_produktow Identyfikatory_produktow { get; set; }

    public virtual Kategorie_produktow Kategorie_produktow { get; set; }

}

}
