
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Krecik
{

using System;
    using System.Collections.Generic;
    
public partial class Zamowienia
{

    public int Id_zamowienia { get; set; }

    public string Id_klienta { get; set; }

    public string Id_produktu { get; set; }

    public string Etykieta_produktu { get; set; }

    public string Ilosc { get; set; }

    public string Kwota { get; set; }

    public string Id_faktury { get; set; }

    public string Data_zlozenia_zaowienia { get; set; }

    public string Data_zrealizowania_zamowienia { get; set; }



    public virtual Klienci Klienci { get; set; }

    public virtual Faktury Faktury { get; set; }

    public virtual Identyfikatory_produktow Identyfikatory_produktow { get; set; }

}

}
